Newaz_1271713_Code_First/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Newaz_1271713_Code_First.Models
{
    public class Category
    {
        [Key]
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}

Newaz_1271713_Code_First/Models/OrderDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Newaz_1271713_Code_First.Models
{
    public class OrderDetail
    {
        [Key]
        public int OrderDetailID { get; set; }

        public int OrderID { get; set; }
        public OrderMaster OrderMaster { get; set; }

        public int ProductID { get; set; }

        [Required(ErrorMessage ="Must be filled")]
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
    }
}

Newaz_1271713_Code_First/Models/OrderMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Newaz_1271713_Code_First.Models
{
    public class OrderMaster
    {

        [Key]
        public int OrderID { get; set; }
        [StringLength(50)]
        public string OrderNote { get; set; }

        public DateTime OrderDate { get; set; }
        public string AddressProofImage { get; set; }
        public Nullable<bool> Terms { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Newaz_1271713_Code_First/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Newaz_1271713_Code_First.Models
{
    public class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }

        public int CategoryID { get; set; }

    }
}

Newaz_1271713_Code_First/Models/ViewModels/OrderVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Newaz_1271713_Code_First.Models.ViewModels
{
    public class OrderVM
    {
 
        public int OrderID { get; set; }
        public string OrderNote { get; set; }
        public DateTime OrderDate { get; set; }
        public string AddressProofImage { get; set; }
        public Nullable<bool> Terms { get; set; }
        public int OrderDetailID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }

    }
}

Newaz_1271713_Code_First/Controllers/OrderPlaceController.cs
using Newaz_1271713_Code_First.DAL;
using Newaz_1271713_Code_First.Models;
using Newaz_1271713_Code_First.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Newaz_1271713_Code_First.Controllers
{
    public class OrderPlaceController : Controller
    {
        public OrderContext db = new OrderContext();
        // GET: OrderPlace
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult getProductCategories()
        {
            List<Category> categories = new List<Category>();
            categories = db.Categories.OrderBy(a => a.CategoryName).ToList();

            return new JsonResult { Data = categories, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

        }

        public JsonResult getProducts(int categoryID)
        {
            List<Product> products = new List<Product>();

            products = db.Products.Where(a => a.CategoryID.Equals(categoryID)).OrderBy(a => a.ProductName).ToList();

            return new JsonResult { Data = products, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult save(OrderMaster order, HttpPostedFileBase file)
        {
            bool status = false;


            if (file != null)
            {
                string folderPath = Server.MapPath("~/Images/");
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string filePath = Path.Combine(folderPath, fileName);
                file.SaveAs(filePath);

                order.AddressProofImage = filePath;
            }

            var isValidModel = TryUpdateModel(order);

            if (isValidModel)
            {
                db.OrderMasters.Add(order);
                db.SaveChanges();
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }



        [HttpGet]
        public ActionResult Edit(int id)
        {
            OrderMaster orderMaster = db.OrderMasters.Include(o => o.OrderDetails).SingleOrDefault(o => o.OrderID == id);
            if (orderMaster == null)
            {
                return HttpNotFound();
            }

            return View(orderMaster);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrderMaster orderMaster, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string folderPath = Server.MapPath("~/Images/");
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string filePath = Path.Combine(folderPath, fileName);
                    file.SaveAs(filePath);

                    orderMaster.AddressProofImage = filePath;
                }

                db.Entry(orderMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(orderMaster);
        }




        public ActionResult List()
        {

            var orderDetails = db.OrderDetails.Include("OrderMaster").ToList();


            var orderVMs = orderDetails.Select(o => new OrderVM
            {
                OrderDetailID = o.OrderDetailID,
                ProductID = o.ProductID,
                OrderID = o.OrderID,
                Quantity = o.Quantity,
                Rate = o.Rate,
                OrderDate = o.OrderMaster.OrderDate,
                OrderNote = o.OrderMaster.OrderNote,
                AddressProofImage = o.OrderMaster.AddressProofImage,
                Terms = o.OrderMaster.Terms
            }).ToList();

            return View(orderVMs);
        }


        public ActionResult Delete(int id)
        {
            OrderMaster orderMaster = db.OrderMasters.Find(id);
            if (orderMaster == null)
            {
                return HttpNotFound();
            }

            return View(orderMaster);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id)
        {
            OrderMaster orderMaster = db.OrderMasters.Find(id);
            if (orderMaster == null)
            {
                return HttpNotFound();
            }

            db.OrderMasters.Remove(orderMaster);
            db.SaveChanges();

            return RedirectToAction("List");
        }
    }
}

Newaz_1271713_Code_First/Views/OrderPlace/Delete.cshtml
@model Newaz_1271713_Code_First.Models.OrderMaster

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderMaster</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderNote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressProofImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressProofImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Terms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Terms)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

Newaz_1271713_Code_First/Views/OrderPlace/Edit.cshtml
@model Newaz_1271713_Code_First.Models.OrderMaster

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>OrderMaster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderID)


        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNote, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressProofImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressProofImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressProofImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Terms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Terms)
                    @Html.ValidationMessageFor(model => model.Terms, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @foreach (var item in Model.OrderDetails)
        {
            <div class="form-group">
                @Html.LabelFor(model => item.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => item.Quantity)
                        @Html.ValidationMessageFor(model => item.Quantity, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => item.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => item.Rate)
                        @Html.ValidationMessageFor(model => item.Rate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="navbar-btn">
    @Html.ActionLink("Back to List", "List")
</div>

Newaz_1271713_Code_First/Views/OrderPlace/Index.cshtml
<h2>Order Your Favourite Bike!</h2>
<div class="container">

    <div class="master">

        <h2>Order Details</h2>
        <table class="table table-responsive">
            <tr>
                <td>Order Note</td>
                <td>
                    <textarea id="description" class="form-control"></textarea>
                </td>

                <td>Order Date</td>
                <td>
                    <input type="date" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
            </tr>
            <tr>
                <td>Upload Adress Proof Image</td>
                <td>
                    <input type="file" name="ImageFile" id="imageupload" class="form-control" />
                </td>

                <td>Terms!(Agree/Not)</td>
                <td>
                    <input id="bool" type="checkbox" class="form-control">
                </td>
            </tr>

        </table>
    </div>
    <div class="details">
        <h2>
            Order Item Selection
        </h2>
        <table class="table table-responsive">
            <tr>
                <td>Category</td>
                <td>Product</td>
                <td>Quantity</td>
                <td>Rate</td>
                <td>&nbsp;</td>
            </tr>
            <tr class="mycontainer" id="mainrow">
                <td>
                    <select id="productCategory" class="pc form-control" onchange="LoadProduct(this)">
                        <option>Select</option>
                    </select>
                    <span class="error">Select Category</span>
                </td>
                <td>
                    <select id="product" class="product form-control">
                        <option>Select</option>
                    </select>
                    <span class="error">Select product</span>
                </td>
                <td>
                    <input type="text" id="quantity" class="quantity form-control" />
                    <span class="error">Valid quantity required</span>
                </td>
                <td>
                    <input type="text" id="rate" class="rate form-control" />
                    <span class="error">Valid rate required</span>
                </td>
                <td>
                    <input type="button" id="add" value="add" style="width:80px" class="btn btn-success" />
                </td>
            </tr>
        </table>
        <div id="orderItems">
            @Html.Partial("_PartialPage1")
        </div>
        <div style="padding:10px 0; text-align:right">
            <input id="submit" type="button" value="Save Order" class="btn btn-primary" style="padding:10px 20px" />

        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "List")
</div>

<script src="~/Scripts/IndexScript.js"></script>


<script>
    $(document).ready(function () {
        $('#submit').click(function () {
            var formData = new FormData();
            formData.append('file', $('#imageupload')[0].files[0]);

            $.ajax({
                type: 'POST',
                url: '/OrderPlace/save',
                data: formData,
                contentType: false,
                processData: false

            })
        })
    })
</script>




<style>
    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    tr.error {
        background-color: rgba(255,0,0,0.35);
    }
</style>

Newaz_1271713_Code_First/Views/OrderPlace/List.cshtml
@model List<Newaz_1271713_Code_First.Models.ViewModels.OrderVM>



@Html.ActionLink("Place An Order", "Index")

<h2>List</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Product ID</th>
            <th>Quantity</th>
            <th>Rate</th>
            <th>Order Date</th>
            <th>Order Note</th>
            <th>Address Proof Image</th>
            <th>Terms</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var order in Model)
        {
            <tr>
                <td>@order.OrderID</td>
                <td>@order.ProductID</td>
                <td>@order.Quantity</td>
                <td>@order.Rate</td>
                <td>@order.OrderDate.ToString("yyyy-MM-dd")</td>
                <td>@order.OrderNote</td>
                <td><img src="~/Images/@order.AddressProofImage" height="80" width="80" /></td>
                <td>@order.Terms</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = order.OrderID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = order.OrderID })
                </td>
            </tr>
        }

    </tbody>
</table>

Newaz_1271713_Code_First/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Newaz_CodeFirst</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>




</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Click To Buy a Bike!", "Index", "OrderPlace", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Order List", "List")</li>

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Raihan Newaz</p>
        </footer>
    </div>
</body>
</html>

Newaz_1271713_Code_First/Views/Shared/_PartialPage1.cshtml
<table class="table table-responsive" id="orderdetailsItems"></table>
<span id="orderItemError" style="color:red"></span>